name: Sync Kaggle Notebooks

on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip kaggle nbconvert

      - name: Configure Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download Top 3 Notebooks
        run: |
          mkdir -p "Kaggle-top-3-notebook"
          
          # 1. Manga Sales Notebook
          kaggle kernels pull adelanseur/manga-sales-eda-ml -p "Kaggle-top-3-notebook" && \
            mv "Kaggle-top-3-notebook/manga-sales-eda-ml.ipynb" "Kaggle-top-3-notebook/1_Manga_Sales.ipynb" || \
            echo "❌ Failed to download Manga Sales notebook"

          # 2. clustering-pca-k-means
          kaggle kernels pull adelanseur/clustering-pca-k-means -p "Kaggle-top-3-notebook" && \
            mv "Kaggle-top-3-notebook/clustering-pca-k-means.ipynb" "Kaggle-top-3-notebook/2_clustering-pca-k-means.ipynb" || \
            echo "❌ Failed to download Second Notebook"

          # 3. nlp-gru-emotions-analysis
          kaggle kernels pull adelanseur/nlp-gru-emotions-analysis -p "Kaggle-top-3-notebook" && \
            mv "Kaggle-top-3-notebook/nlp-gru-emotions-analysis.ipynb" "Kaggle-top-3-notebook/3_nlp-gru-emotions-analysis.ipynb" || \
            echo "❌ Failed to download Third Notebook"

      - name: Execute and Convert to HTML
        run: |
          cd Kaggle-top-3-notebook
          for nb in *.ipynb; do
            jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=600 "$nb" --output "${nb%.ipynb}.html" || \
              echo "⚠️ Failed to convert $nb"
          done
          cd ..

      - name: Move HTML to docs for GitHub Pages
        run: |
          mkdir -p docs
          cp Kaggle-top-3-notebook/*.html docs/

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -f Kaggle-top-3-notebook/* docs/*
          git status
          git commit -m "chore: Sync top 3 notebooks and HTMLs $(date +'%Y-%m-%d')" || \
            (echo "⚠️ No changes to commit" && git commit --allow-empty -m "Debug: Empty commit")
          git push
