name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: |
          pip install --upgrade pip
          pip install kaggle==1.6.0
          which kaggle
          kaggle --version

      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          # Create PROPERLY formatted JSON
          echo '{
            "username": "'${{ secrets.KAGGLE_USERNAME }}'",
            "key": "'${{ secrets.KAGGLE_KEY }}'"
          }' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          echo "=== Config Verification ==="
          cat ~/.kaggle/kaggle.json | jq .

      - name: Test API Connection
        run: |
          export PATH=$PATH:~/.local/bin
          echo "=== Network Test ==="
          ping -c 3 www.kaggle.com
          curl -v https://www.kaggle.com/api/v1

      - name: Validate Credentials
        run: |
          export PATH=$PATH:~/.local/bin
          echo "=== Authentication Test ==="
          FULL_URL="https://www.kaggle.com/api/v1/users/check?username=${{ secrets.KAGGLE_USERNAME }}"
          echo "Testing URL: $FULL_URL"
          
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Kaggle ${{ secrets.KAGGLE_KEY }}" \
            "$FULL_URL")
          
          echo "HTTP Status: $RESPONSE"
          [ "$RESPONSE" -eq 200 ] || exit 1

      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          echo "Pulling: ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG"
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG -p ./notebooks/
          ls -la ./notebooks/
