name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install kaggle==1.6.0  # Pinned known-working version
          sudo apt-get install -y jq curl

      - name: Create Kaggle Config
        run: |
          mkdir -p ~/.kaggle
          # Triple-checked JSON formatting
          echo "{
            \"username\": \"${{ secrets.KAGGLE_USERNAME }}\",
            \"key\": \"${{ secrets.KAGGLE_KEY }}\"
          }" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

          echo "=== Config File Contents ==="
          cat ~/.kaggle/kaggle.json | jq .
          echo "==========================="

      - name: Validate Credentials
        run: |
          export PATH=$PATH:~/.local/bin
          
          echo "=== Testing Authentication ==="
          echo "Using key starting with: ${KAGGLE_KEY:0:4}..."  # Shows first 4 chars
          
          API_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Kaggle ${{ secrets.KAGGLE_KEY }}" \
            "https://www.kaggle.com/api/v1/users/check")
            
          echo "HTTP Status Code: $API_RESPONSE"
          
          if [ "$API_RESPONSE" -eq 200 ]; then
            echo "✅ Authentication successful!"
          else
            echo "❌ Authentication failed (HTTP $API_RESPONSE)"
            echo "Possible reasons:"
            echo "1. Invalid API key"
            echo "2. Key expired (generate new one)"
            echo "3. Incorrect username"
            echo "4. Network restrictions"
            exit 1
          fi

      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          echo "Pulling notebook..."
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG -p ./notebooks/
