name: Sync Kaggle Notebooks
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Kaggle API
        run: |
          pip install --upgrade pip
          pip install kaggle
          echo "Kaggle version: $(kaggle --version)"
          
      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
      - name: Verify Setup
        run: |
          export PATH=$PATH:~/.local/bin
          kaggle config view
          kaggle kernels list --user ${{ secrets.KAGGLE_USERNAME }} --page-size 1
          
      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG -p ./notebooks/
          
      - name: List Downloaded Files
        run: ls -la ./notebooks/
