name: Sync Kaggle Notebooks
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          # Verify the file was created
          ls -la ~/.kaggle/
          cat ~/.kaggle/kaggle.json | jq 'del(.key)' # Prints config without exposing key
          
      - name: Test Kaggle API
        run: |
          kaggle config view
          kaggle kernels list --user ${{ secrets.KAGGLE_USERNAME }} # Verify authentication
          
      - name: Pull Notebook
        run: |
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/your-notebook-slug -p ./notebooks/
