name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle API (Latest)
        run: |
          pip install --upgrade pip
          pip install --force-reinstall git+https://github.com/Kaggle/kaggle-api.git@master
          kaggle --version

      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{
            "username":"adelanseur",
            "key":"${{ secrets.KAGGLE_KEY }}",
            "allow_private":true,
            "verify_ssl":true
          }' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          echo "=== API Test ==="
          kaggle config view

      - name: Verify Notebook Access
        run: |
          export PATH=$PATH:~/.local/bin
          echo "=== Testing Access ==="
          kaggle kernels status adelanseur/manga-sales-eda-ml || \
          { echo "Access denied - check notebook visibility"; exit 1; }

      - name: Sync Notebooks
        run: |
          mkdir -p "Kaggle-top-3-notebook"
          
          # Clean previous downloads
          rm -f Kaggle-top-3-notebook/*.ipynb
          
          # Download with retry logic
          for i in {1..3}; do
            kaggle kernels pull adelanseur/manga-sales-eda-ml -p "Kaggle-top-3-notebook" && break || \
            sleep 5
          done
          
          mv "Kaggle-top-3-notebook/manga-sales-eda-ml.ipynb" "Kaggle-top-3-notebook/1_Manga_Sales.ipynb"

      - name: Convert to HTML
        run: |
          cd Kaggle-top-3-notebook
          jupyter nbconvert "1_Manga_Sales.ipynb" --to html
          ls -la *.html

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update: Manga Notebook $(date +'%Y-%m-%d %H:%M')"
          git push
