name: Sync Kaggle Notebooks
on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly sync (Sunday midnight UTC)
  workflow_dispatch:       # Allows manual runs

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install kaggle nbconvert
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
      - name: Download and clean notebook
        run: |
          kaggle kernels pull your-kaggle-username/notebook-slug -p ./notebooks/
          jupyter nbconvert --to notebook --ClearMetadataPreprocessor.enabled=True notebooks/*.ipynb
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update notebooks" || echo "No changes"
          git push
