name: Sync Kaggle Notebooks

on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip kaggle nbconvert ipykernel

      - name: Configure Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Clean Previous Outputs
        run: |
          rm -rf Kaggle-top-3-notebook
          mkdir -p Kaggle-top-3-notebook

      - name: Download Notebooks into Named Subfolders
        run: |
          # Manga Sales
          mkdir -p Kaggle-top-3-notebook/1_Manga_Sales/images
          kaggle kernels pull adelanseur/manga-sales-eda-ml -p Kaggle-top-3-notebook/1_Manga_Sales
          mv Kaggle-top-3-notebook/1_Manga_Sales/manga-sales-eda-ml.ipynb Kaggle-top-3-notebook/1_Manga_Sales/1_Manga_Sales.ipynb

          # Clustering
          mkdir -p Kaggle-top-3-notebook/2_Clustering_PCA_KMeans/images
          kaggle kernels pull adelanseur/clustering-pca-k-means -p Kaggle-top-3-notebook/2_Clustering_PCA_KMeans
          mv Kaggle-top-3-notebook/2_Clustering_PCA_KMeans/clustering-pca-k-means.ipynb Kaggle-top-3-notebook/2_Clustering_PCA_KMeans/2_Clustering_PCA_KMeans.ipynb

          # NLP GRU
          mkdir -p Kaggle-top-3-notebook/3_NLP_GRU_Emotions/images
          kaggle kernels pull adelanseur/nlp-gru-emotions-analysis -p Kaggle-top-3-notebook/3_NLP_GRU_Emotions
          mv Kaggle-top-3-notebook/3_NLP_GRU_Emotions/nlp-gru-emotions-analysis.ipynb Kaggle-top-3-notebook/3_NLP_GRU_Emotions/3_NLP_GRU_Emotions.ipynb

      - name: Execute and Convert to HTML
        run: |
          for folder in Kaggle-top-3-notebook/*/; do
            base=$(basename "$folder")
            ipynb="$folder/$base.ipynb"
            html="$folder/$base.html"

            echo "▶️ Executing $ipynb"
            jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=300 "$ipynb" || echo "⚠️ Execution failed for $ipynb"

            echo "🌐 Converting to HTML: $html"
            jupyter nbconvert --to html --output "$html" "$ipynb" || echo "⚠️ Conversion failed for $ipynb"
          done

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git add -f Kaggle-top-3-notebook/**/*
          git status

          git commit -m "chore: Sync and update notebooks on $(date +'%Y-%m-%d')" || \
            (echo "⚠️ No changes to commit" && git commit --allow-empty -m "chore: No notebook changes but ran successfully")

          git push
