name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle API
        run: |
          pip install --upgrade pip
          pip install --upgrade kaggle==1.6.1  # Explicitly use stable version
          python -c "import kaggle; print(f'Kaggle API version: {kaggle.__version__}')"

      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{
            "username":"adelanseur",
            "key":"${{ secrets.KAGGLE_KEY }}",
            "allow_private":true,
            "verify_ssl":true
          }' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          echo "=== Config Test ==="
          kaggle config view

      - name: Verify Notebook Access
        run: |
          echo "=== Testing API Access ==="
          NOTEBOOK_URL="https://www.kaggle.com/api/v1/kernels/status/adelanseur/manga-sales-eda-ml"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Kaggle ${{ secrets.KAGGLE_KEY }}" "$NOTEBOOK_URL")
          
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ API Access Verified"
          else
            echo "❌ API Access Failed (HTTP $HTTP_STATUS)"
            echo "Required Actions:"
            echo "1. Regenerate API
