name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: |
          pip install --upgrade pip
          pip install kaggle==1.6.0 nbconvert

      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{
            "username":"adelanseur",  # Hardcoded for testing
            "key":"${{ secrets.KAGGLE_KEY }}",
            "allow_private":true
          }' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Direct API Test
        run: |
          export PATH=$PATH:~/.local/bin
          echo "=== Testing Direct API Access ==="
          kaggle kernels status adelanseur/manga-sales-eda-ml

      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          kaggle kernels pull adelanseur/manga-sales-eda-ml -p ./notebooks/ || echo "Pull attempted"
          ls -la ./notebooks/

      - name: Convert to HTML
        if: success() || failure()  # Runs regardless of previous steps
        run: |
          [ -f "./notebooks/manga-sales-eda-ml.ipynb" ] && {
            jupyter nbconvert ./notebooks/*.ipynb --to html
            echo "Conversion successful"
          } || echo "No notebook found to convert"
