name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: |
          pip install --upgrade pip
          pip install kaggle==1.6.0 nbconvert

      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{
            "username":"${{ secrets.KAGGLE_USERNAME }}",
            "key":"${{ secrets.KAGGLE_KEY }}",
            "allow_private":true
          }' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Verify Notebook Visibility
        run: |
          export PATH=$PATH:~/.local/bin
          echo "Checking notebook visibility..."
          NOTEBOOK_URL="https://www.kaggle.com/${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NOTEBOOK_URL")
          
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Notebook is accessible"
          else
            echo "❌ Notebook returned HTTP $HTTP_STATUS"
            echo "Make sure:"
            echo "1. Notebook is public (temporarily)"
            echo "2. URL slug is correct"
            echo "Current URL: $NOTEBOOK_URL"
            exit 1
          fi

      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG -p ./notebooks/
          ls -la ./notebooks/

      - name: Convert to HTML
        run: |
          jupyter nbconvert ./notebooks/*.ipynb --to html
