name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: |
          pip install --upgrade pip
          pip install kaggle==1.6.0 --force-reinstall

      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"adelanseur","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Pull Notebook to Correct Path
        run: |
          # Create target directory structure
          mkdir -p "Kaggle-top-3-notebook"
          
          # Download notebook with proper filename
          kaggle kernels pull adelanseur/manga-sales-eda-ml -p "Kaggle-top-3-notebook"
          
          # Rename to match your desired filename
          mv "Kaggle-top-3-notebook/manga-sales-eda-ml.ipynb" "Kaggle-top-3-notebook/Manga Sales Kaggle notebook.ipynb"
          
          echo "=== Downloaded Files ==="
          ls -la "Kaggle-top-3-notebook/"

      - name: Force Update Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update: Manga Sales Notebook $(date +'%Y-%m-%d %H:%M')" --allow-empty
          git push origin main
