name: Sync Kaggle Notebooks
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Kaggle API
        run: pip install kaggle nbconvert

      - name: Configure Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
      - name: Download Notebook
        run: |
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/your-notebook-slug -p ./notebooks/
          
      - name: Convert to HTML
        run: |
          jupyter nbconvert --to html ./notebooks/*.ipynb
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update notebook [$(date +'%Y-%m-%d')]" || echo "No changes to commit"
          git push
