name: Kaggle Notebook Sync
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: |
          # Clean installation
          pip uninstall -y kaggle || true
          pip install --no-cache-dir kaggle==1.6.0
          sudo chmod a+r /opt/hostedtoolcache/Python/*/x64/lib/python*/site-packages/kaggle/__init__.py

      - name: Configure Credentials (Dual Method)
        run: |
          # Method 1: kaggle.json file
          mkdir -p ~/.kaggle
          echo '{
            "username":"${{ secrets.KAGGLE_USERNAME }}",
            "key":"${{ secrets.KAGGLE_KEY }}"
          }' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          # Method 2: Environment variables (backup)
          echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
          echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV
          
          # Verify both methods
          echo "=== File Contents ==="
          cat ~/.kaggle/kaggle.json
          echo "=== Env Variables ==="
          echo "KAGGLE_USERNAME: $KAGGLE_USERNAME"
          echo "KAGGLE_KEY: ${KAGGLE_KEY:0:4}..."

      - name: Validate Installation
        run: |
          echo "=== Kaggle Path ==="
          which kaggle
          echo "=== Python Path ==="
          which python
          echo "=== Directory Permissions ==="
          ls -la ~/.kaggle/
          echo "=== Config Test ==="
          kaggle config view

      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG -p ./notebooks/
          ls -la ./notebooks/
