name: Sync Kaggle Notebooks
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Kaggle API
        run: |
          pip install --upgrade pip
          pip install kaggle --upgrade
          
      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          # Verify config
          echo "Kaggle config:"
          cat ~/.kaggle/kaggle.json | jq 'del(.key)'
          
      - name: Validate Authentication
        run: |
          export PATH=$PATH:~/.local/bin
          echo "Testing API access..."
          kaggle config view
          kaggle competitions list -s latest  # Correct API call
          
      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          echo "Pulling notebook: ${{ secrets.KAGGLE_USERNAME }}/NOTEBOOK_SLUG"
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/NOTEBOOK_SLUG -p ./notebooks/ || echo "Pull failed"
          ls -la ./notebooks/
          
      - name: Convert to HTML
        run: |
          pip install nbconvert
          jupyter nbconvert ./notebooks/*.ipynb --to html
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update notebook [$(date +'%Y-%m-%d')]" || echo "No changes"
          git push
