name: Sync Kaggle Notebooks
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Kaggle API
        run: |
          pip install --upgrade pip
          pip install kaggle --upgrade
          sudo apt-get install -y jq  # For JSON parsing
          
      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          # Create the config file with proper formatting
          echo '{"username":"'"${{ secrets.KAGGLE_USERNAME }}"'","key":"'"${{ secrets.KAGGLE_KEY }}"'"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          # Verify the file was created correctly
          echo "Kaggle config file contents:"
          cat ~/.kaggle/kaggle.json | jq 'del(.key)'  # Shows config without exposing key
          
          # Verify the file permissions
          ls -la ~/.kaggle/
          
      - name: Validate Authentication
        run: |
          export PATH=$PATH:~/.local/bin
          echo "Testing API access..."
          kaggle config view
          kaggle competitions list --sort-by latest --page-size 1
          
      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          echo "Pulling notebook..."
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/ACTUAL_NOTEBOOK_SLUG -p ./notebooks/
          
      - name: Verify Download
        run: |
          ls -la ./notebooks/
          [ -f "./notebooks/*.ipynb" ] && echo "Download successful!" || echo "Download failed"
