name: Kaggle Notebook Sync
on: [workflow_dispatch]

env:
  KAGGLE_CONFIG_DIR: /home/runner/.kaggle

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: |
          pip install --upgrade pip
          pip install kaggle==1.6.0
          sudo chmod a+r /opt/hostedtoolcache/Python/*/x64/lib/python*/site-packages/kaggle/__init__.py

      - name: Configure Kaggle
        run: |
          mkdir -p $KAGGLE_CONFIG_DIR
          echo '{
            "username":"${{ secrets.KAGGLE_USERNAME }}",
            "key":"${{ secrets.KAGGLE_KEY }}",
            "allow_private":true,
            "verify_ssl":true
          }' > $KAGGLE_CONFIG_DIR/kaggle.json
          chmod 600 $KAGGLE_CONFIG_DIR/kaggle.json
          
          echo "=== Config Verification ==="
          cat $KAGGLE_CONFIG_DIR/kaggle.json | jq .

      - name: Validate Permissions
        run: |
          export PATH=$PATH:~/.local/bin
          echo "=== Testing API Permissions ==="
          kaggle kernels status ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG

      - name: Pull Notebook
        run: |
          export PATH=$PATH:~/.local/bin
          kaggle kernels pull ${{ secrets.KAGGLE_USERNAME }}/YOUR_NOTEBOOK_SLUG -p ./notebooks/
          ls -la ./notebooks/
